# Generated by Django 2.0.8 on 2018-08-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170405_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='l10n.Country', verbose_name='Country'),
        ),
    ]
