# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import satchmo_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Product', verbose_name='Product')),
                ('recurring', models.BooleanField(default=False, help_text='Customer will be charged the regular product price on a periodic basis.', verbose_name='Recurring Billing')),
                ('recurring_times', models.IntegerField(blank=True, help_text='Number of payments which will occur at the regular rate.  (optional)', null=True, verbose_name='Recurring Times')),
                ('expire_length', models.IntegerField(blank=True, help_text='Length of each billing cycle', null=True, verbose_name='Duration')),
                ('expire_unit', models.CharField(choices=[('DAY', 'Days'), ('MONTH', 'Months')], default='DAY', max_length=5, verbose_name='Expire Unit')),
                ('is_shippable', models.IntegerField(choices=[(0, 'No Shipping Charges'), (1, 'Pay Shipping Once'), (2, 'Pay Shipping Each Billing Cycle')], help_text='Is this product shippable?', verbose_name='Shippable?')),
            ],
            options={
                'verbose_name': 'Subscription Product',
                'verbose_name_plural': 'Subscription Products',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', satchmo_utils.fields.CurrencyField(decimal_places=2, help_text='Set to 0 for a free trial.  Leave empty if product does not have a trial.', max_digits=10, null=True, verbose_name='Price')),
                ('expire_length', models.IntegerField(blank=True, help_text='Length of trial billing cycle.  Leave empty if product does not have a trial.', null=True, verbose_name='Trial Duration')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.SubscriptionProduct')),
            ],
            options={
                'verbose_name': 'Trial Terms',
                'verbose_name_plural': 'Trial Terms',
                'ordering': ['-id'],
            },
        ),
    ]
