# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_comments.Comment', verbose_name='Rating')),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
    ]
